'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), fmt=n=>n.toLocaleString('ko-KR'), today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
const families=['유리막 50ml','유리막 105ml','뿌리막 200ml','뿌리막 100ml','케미컬 500ml','케미컬 4L'];
const materials=[],products=[],transactions=[],productions=[];
function material(id,name,slot,qty=1000,versions){const m={id,name,slot,scope:'',memo:'',archived:false,versions:versions||[{id:'공용',qty,state:'사용'}]};materials.push(m);return id;}
material('cap','20파이 검정 안전캡 (호리병용)','캡');material('bottle','50ml 투명 유리병','용기');material('suede','스웨이드 3P','스웨이드',900);material('block','파이어볼 코팅블럭','어플리케이터');material('insert','74×48×105 속지','속지');
function makeProduct(id,name,family,qty=600,sample=false){const front=material(id+'-front',name,'전면 라벨',qty,[{id:'V01',qty:50,state:'중단'},{id:'V02',qty,state:'사용'}]);const back=material(id+'-back',name+' 후면','후면 라벨',qty,[{id:'V01',qty:50,state:'중단'},{id:'V02',qty,state:'사용'}]);let rows;
if(family===0)rows=[['캡','cap','공용'],['유리병','bottle','공용'],['스웨이드','suede','공용'],['어플리케이터','block','공용'],['전면 라벨',front,'V02'],['후면 라벨',back,'V02'],['속지','insert','공용']];
else {const bottle=material(id+'-bottle',families[family]+' 샘플 용기','용기');const cap=material(id+'-cap',families[family]+' 샘플 캡','캡');rows=[['캡',cap,'공용'],['용기',bottle,'공용'],['전면 라벨',front,'V02'],['후면 라벨',back,'V02']];}
materials.find(m=>m.id===front).scope=id;materials.find(m=>m.id===back).scope=id;
products.push({id,name,family,front,back,sample,finished:0,boms:[{name:'BOM 01',locked:false,rows:rows.map(([slot,mid,vid])=>({slot,mid,vid,each:1}))}]});}
makeProduct('FB-LB-004','나노코트 V3. 50ml',0);makeProduct('FB-LB-001','글라스 쉴드 프로 50ml',0,3500);makeProduct('FB-LB-002','글라스 쉴드 50ml',0);makeProduct('FB-LB-003','나노코트 V2 프로 35ml',0,400,true);
families.slice(1).forEach((name,i)=>makeProduct('DEMO-'+(i+1),name+' 샘플',i+1,600,true));
let selected=products[0],productionProduct=selected,bomIndex=0,outMode='out';
const getM=id=>materials.find(m=>m.id===id),getV=(mid,vid)=>getM(mid).versions.find(v=>v.id===vid),bom=()=>productionProduct.boms[bomIndex];
transactions.push({mid:selected.front,vid:'V02',qty:600,type:'입고',date:'2026-09-28',person:'관리자',note:'시연 초기 입고'});
function options(list,value){return list.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('');}
function notify(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('toast').classList.remove('show'),2800);}
function render(){if($('materialsDialog').open)renderMaterialList();const m=getM(selected.front),visible=products.filter(p=>p.name.toLowerCase().includes($('search').value.toLowerCase()));$('productCount').textContent=visible.length+'개';$('products').innerHTML=visible.map(p=>`<button class="product ${p===selected?'active':''}" data-product="${p.id}"><strong>${esc(p.name)}</strong><span>${esc(p.id)}</span></button>`).join('');$('productName').textContent=selected.name;$('productCode').textContent=selected.id+' · 전면 라벨';$('total').textContent=fmt(m.versions.reduce((n,v)=>n+v.qty,0))+'개';$('available').textContent=fmt((m.archived?[]:m.versions.filter(v=>v.state==='사용')).reduce((n,v)=>n+v.qty,0))+'개';$('versionCount').textContent=m.versions.length+'개';$('versions').innerHTML=m.versions.map(v=>`<article class="version"><div class="versiontop"><h4>${esc(v.id)}</h4><span class="badge">${v.state}</span></div><strong>${fmt(v.qty)}<small> 개</small></strong><p>${v.state==='사용'?'생산·출고에 사용할 수 있습니다.':'사용 중단된 버전입니다.'}</p><button data-out="${esc(v.id)}" ${m.archived||v.state!=='사용'?'disabled':''}>출고</button></article>`).join('');const old=$('filter').value;$('filter').innerHTML=options([['','전체 버전'],...m.versions.map(v=>[v.id,v.id])],old);$('history').innerHTML=transactions.filter(t=>t.mid===m.id&&(!$('filter').value||t.vid===$('filter').value)).slice().reverse().map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.type)}</td><td>${esc(t.vid)}</td><td class="num">${t.type==='출고'||t.type==='생산 사용'?'−':'＋'}${fmt(t.qty)}</td><td>${esc(t.person)}</td><td>${esc(t.note)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">등록된 내역이 없습니다.</td></tr>';}
function renderProduction(){const p=productionProduct,b=bom();$('familySelect').innerHTML=options(families.map((f,i)=>[i,f]),p.family);$('finishedProductSelect').innerHTML=options(products.filter(x=>x.family===p.family).map(x=>[x.id,x.name]),p.id);$('bomSelect').innerHTML=options(p.boms.map((b,i)=>[i,b.name+(b.locked?' · 사용됨':' · 편집 가능')]),bomIndex);$('bomState').textContent=b.locked?'사용된 BOM · 잠금':'편집 가능';$('bomHelp').textContent=p.sample?'샘플 구성입니다. 실제 사양에 맞게 종류와 개당 수량을 수정하세요.':b.locked?'사용된 구성은 보존됩니다. 변경하려면 BOM 복사를 눌러주세요.':'제품 기본 구성입니다. 종류·버전·개당 수량을 확인하세요.';$('bomLines').innerHTML=b.rows.map((r,i)=>{const m=getM(r.mid);const candidates=materials.filter(x=>x.id===r.mid||(!x.archived&&x.slot===m.slot&&(!x.scope||x.scope===p.id)&&x.versions.some(v=>v.state==='사용')));return `<tr><td>${esc(r.slot)}</td><td><select aria-label="${esc(r.slot)} 종류" data-row="${i}" data-key="mid" ${b.locked?'disabled':''}>${options(candidates.map(x=>[x.id,x.name+(x.archived?' · 사용 중단':'')]),r.mid)}</select></td><td><select aria-label="${esc(r.slot)} 버전" data-row="${i}" data-key="vid" ${b.locked?'disabled':''}>${options(m.versions.filter(v=>v.state==='사용'||v.id===r.vid).map(v=>[v.id,v.id+(v.state!=='사용'?' · 중단':'')]),r.vid)}</select></td><td><input aria-label="${esc(r.slot)} 개당 수량" type="number" min="1" step="1" value="${r.each}" data-row="${i}" data-key="each" ${b.locked?'disabled':''}></td><td class="num">${fmt(getV(r.mid,r.vid).qty)}개</td><td class="num" data-need="${i}"></td></tr>`;}).join('');renderProductionHistory();updateRequirements();}
function requirements(quantity){const req=new Map();for(const r of bom().rows){if(!Number.isSafeInteger(r.each)||r.each<1)throw Error('개당 수량은 1 이상의 정수여야 합니다.');const key=r.mid+'|'+r.vid,n=r.each*quantity;if(!Number.isSafeInteger(n))throw Error('수량이 너무 큽니다.');const old=req.get(key);req.set(key,{...r,qty:n+(old?old.qty:0)});}return [...req.values()];}
function updateRequirements(){const q=Number($('productionQty').value);let valid=Number.isSafeInteger(q)&&q>0,short=0;try{if(valid)short=requirements(q).filter(r=>getM(r.mid).archived||getV(r.mid,r.vid).state!=='사용'||getV(r.mid,r.vid).qty<r.qty).length;}catch(e){valid=false;}document.querySelectorAll('[data-need]').forEach(el=>{const r=bom().rows[Number(el.dataset.need)],need=r.each*q;el.textContent=valid?fmt(need)+'개':'—';el.classList.toggle('shortage',valid&&getV(r.mid,r.vid).qty<need);});$('finishedSummary').textContent='완제품 재고 '+fmt(productionProduct.finished)+'개';$('productionSummary').textContent=!valid?'생산 수량과 개당 수량을 확인하세요.':short?`부자재 ${short}종 재고 부족 또는 사용 중단 · 생산 등록 불가`:`${fmt(q)}개 생산 · 부자재 ${bom().rows.length}종 자동 사용`;$('productionSummary').classList.toggle('shortage',short>0);}
function completeProduction(q,date,lot,person,note){if(!Number.isSafeInteger(q)||q<1)throw Error('생산 수량은 1 이상의 정수여야 합니다.');if(!date||!lot.trim()||!person.trim())throw Error('날짜, LOT 번호와 담당자를 입력하세요.');const rows=requirements(q);for(const r of rows){const v=getV(r.mid,r.vid);if(getM(r.mid).archived||v.state!=='사용'||v.qty<r.qty)throw Error(getM(r.mid).name+' 재고가 부족하거나 사용 중단 상태입니다.');}if(!Number.isSafeInteger(productionProduct.finished+q))throw Error('완제품 수량이 너무 큽니다.');const rec={id:'PR-'+String(productions.length+1).padStart(4,'0'),pid:productionProduct.id,name:productionProduct.name,bom:bom().name,q,date,lot:lot.trim(),person:person.trim(),note:note.trim(),rows:rows.map(r=>({...r,name:getM(r.mid).name})),cancelled:false};for(const r of rows){getV(r.mid,r.vid).qty-=r.qty;transactions.push({...r,name:getM(r.mid).name,type:'생산 사용',date,person:rec.person,note:rec.id,production:rec.id});}productionProduct.finished+=q;bom().locked=true;productions.push(rec);return rec;}
function cancelProduction(id){const rec=productions.find(r=>r.id===id);if(!rec||rec.cancelled)return false;const p=products.find(p=>p.id===rec.pid);if(p.finished<rec.q)throw Error('완제품 재고가 부족하여 취소할 수 없습니다.');for(const r of rec.rows){getV(r.mid,r.vid).qty+=r.qty;transactions.push({...r,type:'취소 복원',date:today(),person:rec.person,note:rec.id,production:rec.id});}p.finished-=rec.q;rec.cancelled=true;return true;}
function renderProductionHistory(){$('productionHistory').innerHTML=productions.slice().reverse().map(r=>`<tr><td>${r.id}</td><td>${esc(r.name)}<br><small>${esc(r.bom)}</small></td><td>${fmt(r.q)}</td><td>${esc(r.date)}</td><td>${esc(r.lot)}</td><td>${esc(r.person)}</td><td>${esc(r.note)||'—'}</td><td>${r.cancelled?'취소됨':`완료 <button type="button" data-cancel="${r.id}">생산 취소</button>`}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">생산을 등록하면 내역이 표시됩니다.</td></tr>';$('productionTransactions').innerHTML=transactions.filter(t=>t.production).slice().reverse().map(t=>`<tr><td>${esc(t.date)}</td><td>${t.type}</td><td>${esc(t.slot)} · ${esc(t.name||getM(t.mid).name)}</td><td>${esc(t.vid)}</td><td class="num">${t.type==='생산 사용'?'−':'＋'}${fmt(t.qty)}</td><td>${t.production}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">생산 완료 시 부자재 사용 내역이 자동 생성됩니다.</td></tr>';}
function openOut(vid,mode='out'){outMode=mode;$('outTitle').textContent=mode==='out'?'출고 등록':'새 라벨 버전';$('outProduct').textContent=selected.name;$('outError').textContent='';const versions=getM(selected.front).archived?[]:getM(selected.front).versions.filter(v=>v.state==='사용');$('outFields').innerHTML=mode==='out'?`<label class="field">버전<select name="version">${options(versions.map(v=>[v.id,v.id+' · '+fmt(v.qty)+'개']),vid||versions[0]?.id)}</select></label><label class="field">출고 수량<input name="qty" type="number" min="1" step="1" required></label><label class="field">출고 날짜<input name="date" type="date" value="${today()}" required></label><label class="field">담당자<input name="person" maxlength="30" required></label><label class="field">비고<input name="note" maxlength="200"></label>`:'<label class="field">버전명<input name="versionName" maxlength="20" placeholder="예: V03" required></label><p>새 버전은 재고 0개로 시작합니다.</p>';$('outDialog').showModal();}
$('search').oninput=render;$('filter').onchange=render;$('products').onclick=e=>{const b=e.target.closest('[data-product]');if(b){selected=products.find(p=>p.id===b.dataset.product);$('filter').value='';render();}};$('versions').onclick=e=>{const b=e.target.closest('[data-out]');if(b)openOut(b.dataset.out);};$('recordBtn').onclick=()=>openOut();$('versionBtn').onclick=()=>openOut(null,'version');for(const id of ['closeOut','cancelOut'])$(id).onclick=()=>$('outDialog').close();
$('outForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);try{if(outMode==='version'){addMaterialVersion(selected.front,String(f.get('versionName')));}else{const q=Number(f.get('qty')),v=getV(selected.front,f.get('version')),person=String(f.get('person')).trim();if(!Number.isSafeInteger(q)||q<1||!person)throw Error('수량과 담당자를 확인하세요.');if(!v||getM(selected.front).archived||v.state!=='사용'||v.qty<q)throw Error('출고 가능한 재고가 부족합니다.');recordMovement(selected.front,v.id,'출고',q,f.get('date'),person,String(f.get('note')));}$('outDialog').close();render();notify('저장되었습니다.');}catch(err){$('outError').textContent=err.message;}};
$('productionBtn').onclick=()=>{productionProduct=selected;bomIndex=productionProduct.boms.length-1;$('productionDate').value=today();$('productionError').textContent='';renderProduction();$('productionDialog').showModal();};for(const id of ['closeProduction','cancelProductionDialog'])$(id).onclick=()=>$('productionDialog').close();$('familySelect').onchange=e=>{productionProduct=products.find(p=>p.family===Number(e.target.value));bomIndex=productionProduct.boms.length-1;renderProduction();};$('finishedProductSelect').onchange=e=>{productionProduct=products.find(p=>p.id===e.target.value);bomIndex=productionProduct.boms.length-1;renderProduction();};$('bomSelect').onchange=e=>{bomIndex=Number(e.target.value);renderProduction();};$('copyBom').onclick=()=>{const copy=structuredClone(bom());copy.locked=false;copy.name='BOM '+String(productionProduct.boms.length+1).padStart(2,'0');productionProduct.boms.push(copy);bomIndex=productionProduct.boms.length-1;renderProduction();};$('bomLines').onchange=e=>{if(!e.target.dataset.key||bom().locked)return;const r=bom().rows[Number(e.target.dataset.row)],key=e.target.dataset.key;r[key]=key==='each'?Number(e.target.value):e.target.value;if(key==='mid')r.vid=getM(r.mid).versions.find(v=>v.state==='사용').id;renderProduction();};$('productionQty').oninput=updateRequirements;$('productionForm').onsubmit=e=>{e.preventDefault();try{completeProduction(Number($('productionQty').value),$('productionDate').value,$('productionLot').value,$('productionPerson').value,$('productionNote').value);$('productionError').textContent='';render();renderProduction();notify('생산과 부자재 사용 내역을 등록했습니다.');}catch(err){$('productionError').textContent=err.message;}};$('productionHistory').onclick=e=>{const b=e.target.closest('[data-cancel]');if(!b)return;try{if(cancelProduction(b.dataset.cancel)){render();renderProduction();notify('생산을 취소하고 부자재 재고를 복원했습니다.');}}catch(err){$('productionError').textContent=err.message;}};render();

// Material catalog and stock movements share the same records used by every BOM.
const slots=['캡','용기','스웨이드','어플리케이터','전면 라벨','후면 라벨','속지'];
let editingMaterial=null,materialSequence=1;
function linkedBoms(mid){return products.flatMap(p=>p.boms).filter(b=>b.rows.some(r=>r.mid===mid));}
function recordMovement(mid,vid,type,q,date,person,note=''){
  const m=getM(mid),v=getV(mid,vid);
  if(!m||!v||m.archived||v.state!=='사용')throw Error('사용 중인 부자재와 버전을 선택하세요.');
  if(!['입고','출고'].includes(type)||!Number.isSafeInteger(q)||q<1)throw Error('수량은 1 이상의 정수여야 합니다.');
  if(!date||!person.trim())throw Error('날짜와 담당자를 입력하세요.');
  const next=v.qty+(type==='입고'?q:-q);
  if(next<0)throw Error('출고 가능한 재고가 부족합니다.');
  if(!Number.isSafeInteger(next))throw Error('재고 수량이 너무 큽니다.');
  v.qty=next;transactions.push({mid,vid,qty:q,type,date,person:person.trim(),note:note.trim(),name:m.name});
}
function saveMaterial(data){
  const name=data.name.trim(),scope=data.scope||'',slot=data.slot;
  if(!name||name.length>80||!slots.includes(slot))throw Error('부자재명과 구성품 분류를 확인하세요.');
  if(scope&&!products.some(p=>p.id===scope))throw Error('연결 제품을 확인하세요.');
  if(materials.some(m=>m!==editingMaterial&&m.slot===slot&&m.scope===scope&&m.name.toLowerCase()===name.toLowerCase()))throw Error('같은 분류와 제품에 동일한 이름의 부자재가 있습니다.');
  if(editingMaterial){
    if(linkedBoms(editingMaterial.id).length&&(slot!==editingMaterial.slot||scope!==editingMaterial.scope))throw Error('BOM에 연결된 분류와 제품은 변경할 수 없습니다. 새 부자재로 등록하세요.');
    Object.assign(editingMaterial,{name,memo:data.memo.trim(),slot,scope});
  }else{
    const qty=Number(data.qty),vid=data.vid.trim();
    if(!vid||vid.length>20||!Number.isSafeInteger(qty)||qty<0)throw Error('최초 버전과 0 이상의 초기 재고를 입력하세요.');
    let id;do{id='MAT-'+String(materialSequence++).padStart(4,'0');}while(getM(id));
    material(id,name,slot,qty,[{id:vid,qty,state:'사용'}]);editingMaterial=getM(id);Object.assign(editingMaterial,{scope,memo:data.memo.trim()});
    if(qty)transactions.push({mid:id,vid,qty,type:'입고',date:today(),person:'초기 등록',note:'부자재 등록 시 초기 재고',name});
  }
  return editingMaterial;
}
function addMaterialVersion(mid,name){const m=getM(mid),id=name.trim();if(m.archived)throw Error('사용 중단된 부자재입니다.');if(!id||id.length>20||m.versions.some(v=>v.id.toLowerCase()===id.toLowerCase()))throw Error('중복되지 않는 버전명을 입력하세요.');m.versions.push({id,qty:0,state:'사용'});}
function renderMaterialList(){
  const query=$('materialSearch').value.toLowerCase(),category=$('materialCategory').value;
  const list=materials.filter(m=>(!m.archived||$('showArchived').checked)&&(!category||m.slot===category)&&(m.name.toLowerCase().includes(query)||m.id.toLowerCase().includes(query)));
  $('materialList').innerHTML=list.map(m=>`<tr class="${m===editingMaterial?'selected-material':''}"><td><strong>${esc(m.name)}</strong><br><small>${esc(m.id)}</small></td><td>${esc(m.slot)}</td><td class="num">${fmt(m.archived?0:m.versions.filter(v=>v.state==='사용').reduce((n,v)=>n+v.qty,0))}개</td><td class="num">${fmt(m.versions.reduce((n,v)=>n+v.qty,0))}개</td><td>${m.archived?'사용 중단':'사용'}</td><td><button type="button" data-manage="${esc(m.id)}">관리</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">해당하는 부자재가 없습니다.</td></tr>';
}
function selectMaterial(m){
  editingMaterial=m;$('materialEditorTitle').textContent=m?'부자재 정보 수정':'새 부자재 등록';$('materialName').value=m?.name||'';$('materialSlot').innerHTML=options(slots.map(s=>[s,s]),m?.slot||'캡');$('materialScope').innerHTML=options([['','공용 · 모든 제품'],...products.map(p=>[p.id,p.name])],m?.scope||'');
  const connected=m&&linkedBoms(m.id).length>0;$('materialSlot').disabled=!!connected;$('materialScope').disabled=!!connected;$('materialMemo').value=m?.memo||'';$('initialMaterialFields').hidden=!!m;$('materialInitialVersion').value='공용';$('materialInitialQty').value='0';$('archiveMaterial').hidden=!m;$('archiveMaterial').textContent=m?.archived?'사용 재개':'사용 중단';$('materialError').textContent='';$('materialStockError').textContent='';$('materialStockPanel').hidden=!m;
  $('materialMovementDate').value=today();$('materialMovementQty').value='';$('newMaterialVersion').value='';renderMaterialList();if(m)renderMaterialStock();
}
function renderMaterialStock(){
  const m=editingMaterial;if(!m)return;
  $('materialStockTitle').textContent=m.name+' · 버전별 재고';$('materialLinkedBoms').textContent='연결된 BOM '+linkedBoms(m.id).length+'개';
  $('materialVersions').innerHTML=m.versions.map((v,i)=>`<tr><td>${esc(v.id)}</td><td class="num">${fmt(v.qty)}개</td><td>${v.state}</td><td><button type="button" data-version-state="${i}">${v.state==='사용'?'사용 중단':'사용 재개'}</button></td></tr>`).join('');
  const old=$('materialMovementVersion').value;$('materialMovementVersion').innerHTML=options(m.versions.filter(v=>v.state==='사용').map(v=>[v.id,v.id]),old);
  $('materialHistory').innerHTML=transactions.filter(t=>t.mid===m.id).slice().reverse().map(t=>`<tr><td>${esc(t.date)}</td><td>${esc(t.type)}</td><td>${esc(t.vid)}</td><td class="num">${t.type==='출고'||t.type==='생산 사용'?'−':'＋'}${fmt(t.qty)}</td><td>${esc(t.person)}</td><td>${esc(t.note)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">등록된 내역이 없습니다.</td></tr>';
}
function refreshMaterialViews(){render();renderMaterialList();if(editingMaterial)renderMaterialStock();if($('productionDialog').open)renderProduction();}
$('manageMaterials').onclick=()=>{$('materialCategory').innerHTML=options([['','전체 구성품'],...slots.map(s=>[s,s])],'');$('materialSearch').value='';selectMaterial(materials[0]);$('materialsDialog').showModal();};
$('closeMaterials').onclick=()=>{$('materialsDialog').close();render();};$('newMaterial').onclick=()=>selectMaterial(null);
$('materialSearch').oninput=renderMaterialList;$('materialCategory').onchange=renderMaterialList;$('showArchived').onchange=renderMaterialList;
$('materialList').onclick=e=>{const b=e.target.closest('[data-manage]');if(b)selectMaterial(getM(b.dataset.manage));};
$('materialForm').onsubmit=e=>{e.preventDefault();try{saveMaterial({name:$('materialName').value,slot:$('materialSlot').value,scope:$('materialScope').value,memo:$('materialMemo').value,vid:$('materialInitialVersion').value,qty:$('materialInitialQty').value});selectMaterial(editingMaterial);refreshMaterialViews();notify('부자재와 재고 연결을 저장했습니다.');}catch(err){$('materialError').textContent=err.message;}};
$('archiveMaterial').onclick=()=>{if(!editingMaterial)return;editingMaterial.archived=!editingMaterial.archived;selectMaterial(editingMaterial);refreshMaterialViews();notify(editingMaterial.archived?'선택 목록에서 제외했습니다. 기존 기록은 보존됩니다.':'부자재 사용을 재개했습니다.');};
$('materialVersionForm').onsubmit=e=>{e.preventDefault();try{addMaterialVersion(editingMaterial.id,$('newMaterialVersion').value);$('newMaterialVersion').value='';$('materialStockError').textContent='';refreshMaterialViews();notify('새 버전을 추가했습니다.');}catch(err){$('materialStockError').textContent=err.message;}};
$('materialVersions').onclick=e=>{const b=e.target.closest('[data-version-state]');if(!b)return;const v=editingMaterial.versions[Number(b.dataset.versionState)];v.state=v.state==='사용'?'중단':'사용';refreshMaterialViews();notify('버전 사용 상태를 변경했습니다.');};
$('materialMovementForm').onsubmit=e=>{e.preventDefault();try{recordMovement(editingMaterial.id,$('materialMovementVersion').value,$('materialMovementType').value,Number($('materialMovementQty').value),$('materialMovementDate').value,$('materialMovementPerson').value,$('materialMovementNote').value);$('materialStockError').textContent='';$('materialMovementQty').value='';refreshMaterialViews();notify('재고와 입출고 내역을 반영했습니다.');}catch(err){$('materialStockError').textContent=err.message;}};
