/* admin-materials.js */
'use strict';
(()=>{
  if(!FB.canAdmin()){location.replace('../../login/index.html');return;}
  const {$,esc,fmt}=UI;let id=null;
  $('adminSettingsRoot').hidden=false;
  $('materialCategory').innerHTML=UI.options([['','전체 구성품'],...['캡','용기','스웨이드','어플리케이터','라벨','속지','케이스'].map(s=>[s,s])],'');
  const current=()=>FB.data.materials.find(m=>m.id===id),linked=()=>FB.data.products.flatMap(p=>p.boms).filter(b=>b.rows.some(r=>r.mid===id)).length;
  function list(){const q=$('materialSearch').value.toLowerCase(),slot=$('materialCategory').value;const items=FB.data.materials.filter(m=>(!m.archived||$('showArchived').checked)&&(!slot||(slot==='라벨'?['전면 라벨','후면 라벨'].includes(m.slot):m.slot===slot))&&(m.name.toLowerCase().includes(q)||m.id.toLowerCase().includes(q)));
    $('materialList').innerHTML=items.map(m=>`<tr class="${m.id===id?'selected-material':''}"><td><strong>${esc(m.name)}</strong><br><small>${esc(m.id)}</small></td><td>${esc(['전면 라벨','후면 라벨'].includes(m.slot)?'라벨':m.slot)}</td><td class="num">${fmt(UI.quantity(m,true))}개</td><td class="num">${fmt(UI.quantity(m))}개</td><td>${m.archived?'단종':'사용'}</td><td><button data-manage="${esc(m.id)}">관리</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">등록된 부자재가 없습니다.</td></tr>';
  }
  function stock(){const m=current();if(!m)return;$('materialStockTitle').textContent=m.name+' · 버전별 재고';$('materialLinkedBoms').textContent='연결된 BOM '+linked()+'개';$('materialVersions').innerHTML=m.versions.map(v=>`<tr><td>${esc(v.id)}</td><td class="num">${fmt(v.qty)}개</td><td>${v.state}</td><td><button data-toggle-version="${esc(v.id)}">${v.state==='사용'?'사용 중단':'사용 재개'}</button></td></tr>`).join('')+`<tr><td colspan="4"><form id="versionForm" class="inline-form"><label>새 버전명<input id="newVersionName" required maxlength="20" placeholder="예: V03"></label><button type="submit">버전 추가</button></form><p id="versionError" role="alert"></p></td></tr>`;
    $('materialHistory').innerHTML=UI.history(FB.data.transactions.filter(t=>t.mid===id));$('versionForm').onsubmit=e=>{e.preventDefault();try{FB.addVersion(id,$('newVersionName').value);UI.toast('재고 0개의 새 버전을 추가했습니다.');}catch(err){$('versionError').textContent=err.message;}};
  }
  function select(materialId){id=materialId;const m=current();$('materialEditorTitle').textContent=m?'부자재 정보 수정':'새 부자재 등록';$('materialName').value=m?.name||'';$('materialSlot').innerHTML=UI.options(FB.slots.map(s=>[s,s]),m?.slot||'캡');$('materialScope').innerHTML=UI.options([['','공용 · 모든 제품'],...FB.data.products.map(p=>[p.id,p.name])],m?.scope||'');$('materialSlot').disabled=!!m&&linked()>0;$('materialScope').disabled=!!m&&linked()>0;$('materialMemo').value=m?.memo||'';$('initialMaterialFields').hidden=!!m;$('materialInitialVersion').value='공용';$('materialInitialQty').value='0';$('archiveMaterial').hidden=!m;$('archiveMaterial').textContent=m?.archived?'단종 해제':'단종 처리';$('materialError').textContent='';$('materialStockPanel').hidden=!m;list();stock();}
  $('newMaterial').onclick=()=>select(null);$('materialSearch').oninput=list;$('materialCategory').onchange=list;$('showArchived').onchange=list;
  $('materialList').onclick=e=>{const b=e.target.closest('[data-manage]');if(b)select(b.dataset.manage);};
  $('materialForm').onsubmit=e=>{e.preventDefault();try{const saved=FB.saveMaterial({id,name:$('materialName').value,slot:$('materialSlot').value,scope:$('materialScope').value,memo:$('materialMemo').value,vid:$('materialInitialVersion').value,qty:Number($('materialInitialQty').value)});select(saved);UI.toast('부자재 설정을 저장했습니다.');}catch(err){$('materialError').textContent=err.message;list();}};
  $('archiveMaterial').onclick=()=>{try{FB.toggleMaterial(id);select(id);UI.toast('부자재 사용 상태를 변경했습니다.');}catch(err){$('materialError').textContent=err.message;}};
  $('materialVersions').onclick=e=>{const b=e.target.closest('[data-toggle-version]');if(!b)return;try{FB.toggleVersion(id,b.dataset.toggleVersion);UI.toast('버전 상태를 변경했습니다.');}catch(err){$('materialError').textContent=err.message;}};
  $('showCatalog').onclick=()=>{$('productSettings').hidden=true;$('showProducts').classList.remove('active');$('catalogSettings').hidden=false;$('bomSettings').hidden=true;$('showCatalog').classList.add('active');$('showBom').classList.remove('active');};
  $('showBom').onclick=()=>{$('productSettings').hidden=true;$('showProducts').classList.remove('active');$('catalogSettings').hidden=true;$('bomSettings').hidden=false;$('showBom').classList.add('active');$('showCatalog').classList.remove('active');BOMView.render();};
  let productId='';
  function productList(){$('adminProductList').innerHTML=FB.data.products.filter(p=>!p.archived||$('showProductArchived').checked).map(p=>`<button class="product" data-product="${esc(p.id)}"><strong>${esc(p.name)}</strong><span>${p.sample?'샘플':'본품'}${p.archived?' · 단종':''}</span></button>`).join('');}
  function selectProduct(id){productId=id||'';const p=FB.data.products.find(p=>p.id===id);$('adminProductName').value=p?.name||'';$('adminProductFamily').innerHTML=UI.options(FB.families.map((f,i)=>[i,f]),p?.family||0);$('adminProductCategory').innerHTML=UI.options(FB.data.productCategories.map(x=>[x,x]),p?.category||'파이어볼');$('adminProductSample').value=String(p?.sample||false);$('archiveProduct').hidden=!p;$('archiveProduct').textContent=p?.archived?'단종 해제':'단종 처리';$('productError').textContent='';}
  $('showProducts').onclick=()=>{$('productSettings').hidden=false;$('catalogSettings').hidden=true;$('bomSettings').hidden=true;$('showProducts').classList.add('active');$('showCatalog').classList.remove('active');$('showBom').classList.remove('active');productList();selectProduct(FB.data.products[0]?.id);};
  $('newProduct').onclick=()=>selectProduct();$('showProductArchived').onchange=productList;$('adminProductList').onclick=e=>{const b=e.target.closest('[data-product]');if(b)selectProduct(b.dataset.product);};
  $('productForm').onsubmit=e=>{e.preventDefault();try{const id=FB.saveProduct({id:productId,name:$('adminProductName').value,family:$('adminProductFamily').value,category:$('adminProductCategory').value,sample:$('adminProductSample').value==='true'});productList();selectProduct(id);UI.toast('완제품을 저장했습니다. BOM에서 부자재를 연결하세요.');}catch(err){$('productError').textContent=err.message;}};
  $('archiveProduct').onclick=()=>{try{FB.toggleProduct(productId);productList();selectProduct(productId);}catch(err){$('productError').textContent=err.message;}};
  $('categoryForm').onsubmit=e=>{e.preventDefault();try{const name=FB.addProductCategory($('newCategoryName').value);$('newCategoryName').value='';$('categoryError').textContent='';const p=FB.data.products.find(p=>p.id===productId);$('adminProductCategory').innerHTML=UI.options(FB.data.productCategories.map(x=>[x,x]),p?.category||name);UI.toast('완제품 분류를 추가했습니다.');}catch(err){$('categoryError').textContent=err.message;}};
  BOMView.bind(true);window.addEventListener('fb-data',()=>{list();stock();$('archiveMaterial').textContent=current()?.archived?'단종 해제':'단종 처리';});select(FB.data.materials[0].id);
})();

